### ISSUE TITLE
Transition to SemVer

### ISSUE THREAD

**Issue by Zsar** [telekom-mms/aurelia-components#68]
### Description

This Repository was started at a time when it was only used by a single project. By now, however, via @mreiche we are involved in two different projects with different development speeds and requirements. Of course, we'd welcome further client projects and the prospective code donors they may bring.

We should now follow the npm Good Practice to [SemVer](https://semver.org/) our releases by the following pattern:
`MAJOR.MINOR.PATCH`
with the following contract:

- MAJOR : _does_ contain breaking changes, may be arbitrarily hard on clients to migrate
- MINOR: contains additions, _may_ break client code if it conflicts with additions (e.g. naming conflicht, shared dependency version conflict)
- PATCH: should not contain breaking changes

We should be ready to treat defect reports re. accidental breakage as bugs with high priority and typically react by

- retraction of release on npmjs
- hotfix release

We should treat dependency updates as follows:

- non-optional dependencies: pass-through their version change
(e.g. if any MAJOR dependency update is contained, treat the next release as MAJOR)
- devDependencies: don't care
- optional (peer) dependencies: only consider resulting usage changes e.g. in jest tests, readme examples or our own, known user code for the purpose of choosing the version
(e.g. if a MAJOR optional peer dependency update happens, but all our code stays the same, treat the next release as FIX)

**Comment by martingrossmann** [comment]
From the beginning of version 1.1.0 `aurelia-components` follows semantic versioning.
